version: '3.8'

services:
  voc-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: voc-frontend-dev
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm start
    networks:
      - voc-network

networks:
  voc-network:
    driver: bridge
